[phases.setup]
nixPkgs = ["php84", "php84Extensions.mongodb", "php84Extensions.redis", "grpc"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-scripts --no-interaction"
]

[start]
cmd = "php-fpm -D && nginx -g 'daemon off;'"